### PR TITLE
Tiny typo in README

### PR DESCRIPTION
**Pull request by fastest963**
Fixed "rbd" typo in README to be "rdb"

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by dwighthubbard** [comment]
Good catch, unfortunetly I can't merge unless you have a CLA on file.

**Comment by fastest963** [comment]
I did sign the CLA but the PR never updated. I guess I'll just force push a new commit hash to re-trigger the CLA check?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by dwighthubbard** [comment]
Looks gtg :+1:

**Pull request merged**
