### PR TITLE
convert template to using Jinja

### PR DESCRIPTION
**Pull request by reneighbor**
* Convert config template to use Jinja
* Add support for slaving to config template
* Early exit on _is_redis_running if pidfile doesn't exist

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by dwighthubbard** [comment]
I believe these changes got committed as part of the pull request that added the slave support.  Can we delete this pull request to prevent confusion?

**Comment by dwighthubbard** [comment]
Disregard my last comment.  Looking at this code this hasn't been applied yet but would be of great value once we get it in.

**Comment by dwighthubbard** [comment]
I think the failed coverage check is within acceptable limits (I've updated the coveralls configuration to be a bit less strict about small coverage drops).  So I'm going to give this a :+1:

**Pull request merged**
