### PR TITLE
Upgrade redis.submodule to 6.2.6

### LINKED ISSUE #152: `pip install redislite` fails on m1 mac
### Overview

`pip install redislite` fails on m1 mac

### Environment

* Python version 3.8.2
* Pip version 21.2.4
* gcc version 12.0.5 (apple arm)

```
% gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### Steps to reproduce

Run `pip install redislite` on m1 mac native terminal (not using Rosetta 2). Note that installing with terminal using Rosetta (x86 compatibility mode) succeeds.

```
    gcc -std=c99 -pedantic -DREDIS_STATIC='' -Wall -W -Wno-missing-field-initializers -O2 -g -ggdb   -I../deps/hiredis -I../deps/linenoise -I../deps/lua/src -c debug.c
    debug.c:750:42: error: no member named '__eip' in 'struct __darwin_arm_thread_state64'
        return (void*) uc->uc_mcontext->__ss.__eip;
                       ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:844:47: error: no member named '__eax' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__eax,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:845:47: error: no member named '__ebx' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__ebx,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:846:47: error: no member named '__ecx' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__ecx,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:847:47: error: no member named '__edx' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__edx,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:848:47: error: no member named '__edi' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__edi,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:849:47: error: no member named '__esi' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__esi,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:850:47: error: no member named '__ebp' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__ebp,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:851:47: error: no member named '__esp' in 'struct __darwin_arm_thread_state64'; did you mean '__sp'?
            (unsigned long) uc->uc_mcontext->__ss.__esp,
                                                  ^~~~~
                                                  __sp
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/arm/_structs.h:139:13: note: '__sp' declared here
            __uint64_t __sp;    /* Stack pointer x31 */
                       ^
    debug.c:852:47: error: no member named '__ss' in 'struct __darwin_arm_thread_state64'; did you mean '__sp'?
            (unsigned long) uc->uc_mcontext->__ss.__ss,
                                                  ^~~~
                                                  __sp
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/arm/_structs.h:139:13: note: '__sp' declared here
            __uint64_t __sp;    /* Stack pointer x31 */
                       ^
    debug.c:853:47: error: no member named '__eflags' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__eflags,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:854:47: error: no member named '__eip' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__eip,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:855:47: error: no member named '__cs' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__cs,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:856:47: error: no member named '__ds' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__ds,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:857:47: error: no member named '__es' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__es,
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:858:47: error: no member named '__fs' in 'struct __darwin_arm_thread_state64'; did you mean '__fp'?
            (unsigned long) uc->uc_mcontext->__ss.__fs,
                                                  ^~~~
                                                  __fp
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/arm/_structs.h:137:13: note: '__fp' declared here
            __uint64_t __fp;    /* Frame pointer x29 */
                       ^
    debug.c:859:47: error: no member named '__gs' in 'struct __darwin_arm_thread_state64'
            (unsigned long) uc->uc_mcontext->__ss.__gs
                            ~~~~~~~~~~~~~~~~~~~~~ ^
    debug.c:861:51: error: no member named '__esp' in 'struct __darwin_arm_thread_state64'; did you mean '__sp'?
        logStackContent((void**)uc->uc_mcontext->__ss.__esp);
                                                      ^~~~~
                                                      __sp
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/arm/_structs.h:139:13: note: '__sp' declared here
            __uint64_t __sp;    /* Stack pointer x31 */
                       ^
    18 errors generated.
    make[1]: *** [debug.o] Error 1
    make: *** [install] Error 2
    ********************************************************************************
    creating build/scripts-3.8
    error: can't copy '/private/var/folders/ky/g05mfhfd4cg20s6tz1vzq4c00000gn/T/pip-install-9wzyr8yb/redislite_a8e4cb73fa444ddb8563f8864de2e505/redis.submodule/bin/redis-server': doesn't exist or not a regular file
    ----------------------------------------
```

### PR DESCRIPTION
**Pull request by tvd0x2a**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

---

Upgrade redis to support installation on devices with Apple M1 chips. Fixes #152. 

I ran `python build_scripts/update_redis_server.py` and then changed the version in `setup.cfg`.

I was not able to test python versions 3.6 or 3.7 on an Apple M1 device. I was able to test with python 3.8 and 3.9, and tests passed.

<details>
<summary>tox output</summary>

```
$ tox -e py38,py39

GLOB sdist-make: /Users/auser/src/redislite/setup.py
py38 inst-nodeps: /Users/auser/src/redislite/.tox/.tmp/package/1/redislite-6.2.6.zip
py38 installed: certifi==2021.10.8,charset-normalizer==2.0.7,cov-core==1.15.0,coverage==5.5,coveralls==3.2.0,docopt==0.6.2,idna==3.3,nose==1.3.7,nose-cov==1.6,psutil==5.8.0,redis==3.5.3,redislite @ file:///Users/auser/src/redislite/.tox/.tmp/package/1/redislite-6.2.6.zip,requests==2.26.0,urllib3==1.26.7
py38 run-test-pre: PYTHONHASHSEED='3826347625'
py38 run-test: commands[0] | nosetests --exe --with-xunit --xunit-file=nosetests.xml --with-coverage --cover-xml --cover-erase --cover-package=redislite --cover-xml-file=cobertura.xml tests
..........................................
Name                             Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------
redislite/__init__.py               22      2      0      0    91%
redislite/__init__/__init__.py      22      2      0      0    91%
redislite/client.py                198      0     52      2    99%
redislite/configuration.py          29      0     10      0   100%
redislite/debug.py                  25      0      4      0   100%
redislite/patch.py                  45      0     16      0   100%
------------------------------------------------------------------
TOTAL                              341      4     82      2    99%
----------------------------------------------------------------------
Ran 42 tests in 7.708s

OK
py39 inst-nodeps: /Users/auser/src/redislite/.tox/.tmp/package/1/redislite-6.2.6.zip
py39 installed: certifi==2021.10.8,charset-normalizer==2.0.7,cov-core==1.15.0,coverage==5.5,coveralls==3.2.0,docopt==0.6.2,idna==3.3,nose==1.3.7,nose-cov==1.6,psutil==5.8.0,redis==3.5.3,redislite @ file:///Users/auser/src/redislite/.tox/.tmp/package/1/redislite-6.2.6.zip,requests==2.26.0,urllib3==1.26.7
py39 run-test-pre: PYTHONHASHSEED='3826347625'
py39 run-test: commands[0] | nosetests --exe --with-xunit --xunit-file=nosetests.xml --with-coverage --cover-xml --cover-erase --cover-package=redislite --cover-xml-file=cobertura.xml tests
..........................................
Name                             Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------
redislite/__init__.py               22      2      0      0    91%
redislite/__init__/__init__.py      22      2      0      0    91%
redislite/client.py                198      0     52      2    99%
redislite/configuration.py          29      0     10      0   100%
redislite/debug.py                  25      0      4      0   100%
redislite/patch.py                  45      0     16      0   100%
------------------------------------------------------------------
TOTAL                              341      4     82      2    99%
----------------------------------------------------------------------
Ran 42 tests in 7.780s

OK
___________________________________ summary ____________________________________
  py38: commands succeeded
  py39: commands succeeded
  congratulations :)

```

</details>

### CODE REVIEW

**Comment by carlosguso** [comment]
What is the current status of this PR?

**Comment by tvd0x2a** [comment]
> What is the current status of this PR?

It’s ready to merge, I believe. 

I think this project may be effectively unmaintained at this point though, so that may not happen. See https://github.com/yahoo/redislite/issues/156 and https://github.com/yahoo/redislite/issues/157.

**Comment by Menda** [comment]
It works like a charm with a Python:3.10 Docker image. Thank you.

**Comment by Uznick** [comment]
Hi, @dwighthubbard! Is there a way to move this forward?

**Review by dwighthubbard — APPROVED** [review]
This looks good to me

**Pull request merged**
