### PR TITLE
If the redis rdb file argument is passed without a path this code will c...

### PR DESCRIPTION
**Pull request by dwighthubbard**
...hange it to use the current working directory for the redisdb

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by zosimos** [comment]
LGTM.

**Comment by jacobtolar** [comment]
:+1:

**Pull request merged**
